# shellcheck shell=bash
# .editorconfig hint: indent_style = space, indent_size = 4
# SPDX-License-Identifier: GPL-3.0-or-later
# shellcheck disable=SC2034
# Constants, defaults, version, globals

# --- File and directory name constants ---
SELF_SCRIPT_NAME="sui-control.sh"
CONFIG_FILE_NAME="sui-control.conf"
ACME_CERT_SCRIPT_NAME="acme-cert.sh"
DB_CONFIG_SCRIPT_NAME="s-ui-db-configure.sh"

# --- FHS paths (set by resolve_layout() in utils.sh) ---
CONFIG_DIR=""
RUNTIME_DIR=""
RUNTIME_BIN_DIR=""
RUNTIME_SYSTEMD_DIR=""
RUNTIME_DATA_DIR=""
RUNTIME_CERT_DIR=""
RUNTIME_ACME_DIR=""

# --- System integration ---
SYSTEMD_DST_DIR="/etc/systemd/system"
SYSTEMD_CONTROL_SERVICE_NAME="sui-control.service"
SYSTEMD_RENEW_SERVICE_NAME="sui-control-renew.service"
SYSTEMD_RENEW_TIMER_NAME="sui-control-renew.timer"
CRON_DST_DIR="/etc/cron.d"
CRON_FILE_NAME="sui-control-renew"
S6_SERVICE_DIR="/etc/s6/sui-control"

# --- User ---
SUI_CONTROL_USER="sui-control"

# --- Default configuration values ---
DEFAULT_DOMAIN=""
DEFAULT_TZ=""
DEFAULT_TIMER_ON_CALENDAR="Mon *-*-* 03:00:00"
DEFAULT_TIMER_RANDOM_DELAY="1h"
DEFAULT_TIMER_ON_CALENDAR_IP="daily"
DEFAULT_TIMER_RANDOM_DELAY_IP="2h"
DEFAULT_CERT_MODE="selfsigned"
DEFAULT_SELF_SIGNED_DAYS="825"
DEFAULT_SUI_PANEL_PORT="2095"
DEFAULT_SUI_SUBSCRIPTION_PORT="2096"
DEFAULT_SUI_PANEL_PATH="panel"
DEFAULT_SUI_SUBSCRIPTION_PATH="sub"
SELF_SIGNED_DIR_NAME="selfsigned"
DEFAULT_INIT_SYSTEM="auto"

# --- Docker images ---
DEFAULT_SUI_IMAGE="alireza7/s-ui:latest"
SUI_IMAGE="${SUI_IMAGE:-$DEFAULT_SUI_IMAGE}"
DEFAULT_CURL_TEST_IMAGE="curlimages/curl:latest"
DEFAULT_CONTAINER_STAMP=""
CURL_TEST_IMAGE="${CURL_TEST_IMAGE:-$DEFAULT_CURL_TEST_IMAGE}"
DEFAULT_ACME_IMAGE="neilpang/acme.sh:latest"
ACME_IMAGE="${ACME_IMAGE:-$DEFAULT_ACME_IMAGE}"

# --- Docker runtime ---
CONTAINER_NAME="s-ui"
DOCKER_NETWORK="s-ui"
DB_TIMEOUT="60"
DB_POLL_INTERVAL="2"

# --- Terminal color codes (interpreted by printf %b) ---
COLOR_INFO='\033[0;32m'
COLOR_WARN='\033[1;33m'
COLOR_ERROR='\033[0;31m'
COLOR_RESET='\033[0m'

# --- Runtime state ---
SCRIPT_ARG0="$(readlink -f "$0")"
SCRIPT_PATH=""
PACKAGE_DIR=""
CURRENT_COMMAND=""
COMMAND=""
AUTO_CONFIRM="0"
BATCH_INSTALL="0"
INSTALL_GENERATED_USERNAME=""
INSTALL_GENERATED_PASSWORD=""

# --- Configuration (may be overridden by env vars, CLI args, or config file) ---
DOMAIN="${DOMAIN:-$DEFAULT_DOMAIN}"
TZ="${TZ:-$DEFAULT_TZ}"
TIMER_ON_CALENDAR="${TIMER_ON_CALENDAR:-$DEFAULT_TIMER_ON_CALENDAR}"
TIMER_RANDOM_DELAY="${TIMER_RANDOM_DELAY:-$DEFAULT_TIMER_RANDOM_DELAY}"
CERT_MODE="${CERT_MODE:-$DEFAULT_CERT_MODE}"
SELF_SIGNED_DAYS="${SELF_SIGNED_DAYS:-$DEFAULT_SELF_SIGNED_DAYS}"
SUI_PANEL_PORT="${SUI_PANEL_PORT:-$DEFAULT_SUI_PANEL_PORT}"
SUI_SUBSCRIPTION_PORT="${SUI_SUBSCRIPTION_PORT:-$DEFAULT_SUI_SUBSCRIPTION_PORT}"
SUI_PANEL_PATH="${SUI_PANEL_PATH:-$DEFAULT_SUI_PANEL_PATH}"
SUI_SUBSCRIPTION_PATH="${SUI_SUBSCRIPTION_PATH:-$DEFAULT_SUI_SUBSCRIPTION_PATH}"
CLI_PANEL_PORT_SET=""
CLI_SUBSCRIPTION_PORT_SET=""
CLI_PANEL_PATH_SET=""
CLI_SUBSCRIPTION_PATH_SET=""
CLI_IP_CERT_SET=""
INIT_SYSTEM="${INIT_SYSTEM:-$DEFAULT_INIT_SYSTEM}"
CONTAINER_STAMP="${CONTAINER_STAMP:-$DEFAULT_CONTAINER_STAMP}"
INBOUND_PORTS=""
