# shellcheck shell=bash
# .editorconfig hint: indent_style = space, indent_size = 4
# SPDX-License-Identifier: GPL-3.0-or-later
# shellcheck disable=SC2034
# Constants, defaults, version, globals

SCRIPT_VERSION="1.3.0"

# --- File and directory name constants ---
SELF_SCRIPT_NAME="sui-control.sh"
CONFIG_FILE_NAME="sui-control.conf"
COMPOSE_FILE_NAME="docker-compose.yml"
ACME_CERT_SCRIPT_NAME="acme-cert.sh"
DB_CONFIG_SCRIPT_NAME="s-ui-db-configure.sh"
SYSTEMD_DIR_NAME="systemd"
SYSTEMD_SERVICE_NAME="s-ui-cert-renew.service"
SYSTEMD_TIMER_NAME="s-ui-cert-renew.timer"

# --- Default configuration values ---
DEFAULT_INSTALL_DIR="/opt/s-ui"
DEFAULT_DOMAIN=""
DEFAULT_TZ=""
DEFAULT_DATA_DIR="./db"
DEFAULT_CERT_DIR="./cert"
DEFAULT_ACME_DIR="./acme"
DEFAULT_BIN_DIR="./bin"
DEFAULT_SYSTEMD_DST_DIR="/etc/systemd/system"
DEFAULT_TIMER_ON_CALENDAR="Mon *-*-* 03:00:00"
DEFAULT_TIMER_RANDOM_DELAY="1h"
DEFAULT_CERT_MODE="selfsigned"
DEFAULT_SELF_SIGNED_DAYS="825"
DEFAULT_SUI_PANEL_PORT="2095"
DEFAULT_SUI_SUBSCRIPTION_PORT="2096"
DEFAULT_SUI_PANEL_PATH="panel"
DEFAULT_SUI_SUBSCRIPTION_PATH="sub"
SELF_SIGNED_DIR_NAME="selfsigned"

# --- Terminal color codes (interpreted by printf %b) ---
COLOR_INFO='\033[0;32m'
COLOR_WARN='\033[1;33m'
COLOR_ERROR='\033[0;31m'
COLOR_RESET='\033[0m'

# --- Runtime state ---
SCRIPT_ARG0="$0"
SCRIPT_PATH=""
CURRENT_COMMAND=""
COMMAND=""
AUTO_CONFIRM="0"
BATCH_INSTALL="0"
RUNTIME_INSTALL_DIR=""
INSTALL_GENERATED_USERNAME=""
INSTALL_GENERATED_PASSWORD=""

# --- Configuration (may be overridden by env vars, CLI args, or config file) ---
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}"
DOMAIN="${DOMAIN:-$DEFAULT_DOMAIN}"
TZ="${TZ:-$DEFAULT_TZ}"
DATA_DIR="$DEFAULT_DATA_DIR"
CERT_DIR="$DEFAULT_CERT_DIR"
ACME_DIR="$DEFAULT_ACME_DIR"
BIN_DIR="$DEFAULT_BIN_DIR"
SYSTEMD_DST_DIR="$DEFAULT_SYSTEMD_DST_DIR"
TIMER_ON_CALENDAR="${TIMER_ON_CALENDAR:-$DEFAULT_TIMER_ON_CALENDAR}"
TIMER_RANDOM_DELAY="${TIMER_RANDOM_DELAY:-$DEFAULT_TIMER_RANDOM_DELAY}"
CERT_MODE="${CERT_MODE:-$DEFAULT_CERT_MODE}"
SELF_SIGNED_DAYS="${SELF_SIGNED_DAYS:-$DEFAULT_SELF_SIGNED_DAYS}"
SUI_PANEL_PORT="${SUI_PANEL_PORT:-$DEFAULT_SUI_PANEL_PORT}"
SUI_SUBSCRIPTION_PORT="${SUI_SUBSCRIPTION_PORT:-$DEFAULT_SUI_SUBSCRIPTION_PORT}"
SUI_PANEL_PATH="${SUI_PANEL_PATH:-$DEFAULT_SUI_PANEL_PATH}"
SUI_SUBSCRIPTION_PATH="${SUI_SUBSCRIPTION_PATH:-$DEFAULT_SUI_SUBSCRIPTION_PATH}"
CLI_PANEL_PORT_SET=""
CLI_SUBSCRIPTION_PORT_SET=""
CLI_PANEL_PATH_SET=""
CLI_SUBSCRIPTION_PATH_SET=""
